import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Rocket, Lock, CreditCard, Hammer, Brain, Globe, BarChart3, Shield, Check, X } from "lucide-react";
import AuthGuard from "@/components/AuthGuard";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";

const epics = [
  {
    num: 1,
    title: "Landing Page",
    icon: Rocket,
    color: "text-primary",
    bg: "bg-primary/10",
    details: [
      "Hero with value proposition",
      "Product demo / interactive preview",
      "Social proof & testimonials",
      "CTA to sign up",
    ],
  },
  {
    num: 2,
    title: "Auth & Login",
    icon: Lock,
    color: "text-primary",
    bg: "bg-primary/10",
    details: [
      "Email/password signup and login",
      "OAuth (Google, Apple)",
      "Email verification flow",
      "Password reset",
    ],
  },
  {
    num: 3,
    title: "Subscriptions",
    icon: CreditCard,
    color: "text-amber-warm",
    bg: "bg-amber-warm/10",
    details: [
      "Free, Pro ($9/mo), Premium ($19/mo), Enterprise tiers",
      "Stripe integration for billing",
      "Usage-based limits per tier",
      "Upgrade / downgrade flows",
    ],
  },
  {
    num: 4,
    title: "Resume Builder",
    icon: Hammer,
    color: "text-primary",
    bg: "bg-primary/10",
    details: [
      "AI-powered layout & theme selector (guided wizard)",
      "Upload artifacts: old resumes, interview answers, metrics",
      "Drag-and-drop section editor (non-technical friendly)",
      "Real-time preview with multiple layouts",
      "Template library (modern, classic, creative, minimal)",
    ],
  },
  {
    num: 5,
    title: "AI Tailoring",
    icon: Brain,
    color: "text-amber-warm",
    bg: "bg-amber-warm/10",
    details: [
      "Paste a JD — AI tailors resume to match",
      "Keyword optimization & gap analysis",
      "Tone and language adjustment",
      "AI resume agent: conversational chatbot for visitors",
      "Powered by the Dark Factory agentic workflow",
    ],
  },
  {
    num: 6,
    title: "Publish & Share",
    icon: Globe,
    color: "text-primary",
    bg: "bg-primary/10",
    details: [
      "One-click publish to yourname.agenticresume.com",
      "Custom domain support",
      "Link social media (LinkedIn, GitHub, portfolio)",
      "QR code generation",
      "PDF export",
    ],
  },
  {
    num: 7,
    title: "Analytics & SEO",
    icon: BarChart3,
    color: "text-amber-warm",
    bg: "bg-amber-warm/10",
    details: [
      "View count, unique visitors, time on page",
      "Section attention heatmap",
      "SEO meta tags auto-generated by AI",
      "Open Graph image generation",
      "Sitemap & robots.txt auto-configured",
    ],
  },
  {
    num: 8,
    title: "Security",
    icon: Shield,
    color: "text-primary",
    bg: "bg-primary/10",
    details: [
      "SOC 2 awareness / encryption at rest",
      "Row-level security on all user data",
      "GDPR-compliant data handling",
      "Password-protected resume sharing",
      "Rate limiting on public endpoints",
    ],
  },
];

const tiers = [
  { name: "Free", price: "$0", features: { resumes: "1", templates: "Basic", customDomain: false, aiTailoring: false, resumeAgent: false, analytics: false, support: "Community", api: false } },
  { name: "Pro", price: "$9/mo", features: { resumes: "Unlimited", templates: "All", customDomain: true, aiTailoring: "Limited", resumeAgent: false, analytics: false, support: "Email", api: false } },
  { name: "Premium", price: "$19/mo", features: { resumes: "Unlimited", templates: "All", customDomain: true, aiTailoring: "Unlimited", resumeAgent: true, analytics: true, support: "Priority", api: false } },
  { name: "Enterprise", price: "Custom", features: { resumes: "Unlimited", templates: "All + Custom", customDomain: true, aiTailoring: "Unlimited", resumeAgent: true, analytics: true, support: "Dedicated", api: true } },
];

const featureLabels: Record<string, string> = {
  resumes: "Resumes",
  templates: "Templates",
  customDomain: "Custom Domain",
  aiTailoring: "AI Tailoring",
  resumeAgent: "Resume Agent",
  analytics: "Analytics",
  support: "Support",
  api: "API Access",
};

const FeatureValue = ({ value }: { value: string | boolean }) => {
  if (typeof value === "boolean") {
    return value ? <Check className="w-4 h-4 text-primary mx-auto" /> : <X className="w-4 h-4 text-muted-foreground/40 mx-auto" />;
  }
  return <span className="text-foreground font-body text-sm">{value}</span>;
};

const VenturesContent = () => {
  const [activeEpic, setActiveEpic] = useState<string>("1");
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Back nav */}
      <div className="fixed top-0 left-0 right-0 z-50 bg-background/70 backdrop-blur-xl border-b border-border/50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={() => navigate("/")} className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors font-body text-sm">
            <ArrowLeft className="w-4 h-4" /> Back to Portfolio
          </button>
          <span className="font-display text-lg text-primary tracking-wide">Ventures</span>
        </div>
      </div>

      <main className="pt-24 pb-20 px-6 max-w-6xl mx-auto">
        {/* Header */}
        <header className="text-center mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-body font-medium tracking-wide uppercase">
            <Rocket className="w-3.5 h-3.5" /> Venture Concept
          </div>
          <h1 className="font-display text-4xl md:text-5xl text-foreground tracking-wide">
            Agentic Resume Portfolio
          </h1>
          <p className="font-body text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            An AI-powered platform that builds, tailors, and publishes living resume portfolios — 
            complete with a conversational agent that represents you to recruiters and hiring managers.
          </p>
        </header>

        {/* Epic Flow — horizontal scroll */}
        <section className="mb-12">
          <h2 className="font-display text-sm uppercase tracking-[0.2em] text-muted-foreground mb-6">
            User Journey — Epics
          </h2>
          <ScrollArea className="w-full">
            <div className="flex gap-3 pb-4">
              {epics.map((epic, i) => {
                const Icon = epic.icon;
                const isActive = activeEpic === String(epic.num);
                return (
                  <button
                    key={epic.num}
                    onClick={() => setActiveEpic(String(epic.num))}
                    className={`glass-card flex-shrink-0 w-44 p-4 text-left transition-all duration-200 ${isActive ? "ring-1 ring-primary/40 scale-[1.03]" : "hover:bg-card/80"}`}
                  >
                    <div className={`inline-flex p-2 rounded-lg ${epic.bg} mb-2`}>
                      <Icon className={`w-4 h-4 ${epic.color}`} />
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-muted-foreground">{String(epic.num).padStart(2, "0")}</span>
                      <span className="font-display text-sm text-foreground leading-tight">{epic.title}</span>
                    </div>
                    {i < epics.length - 1 && (
                      <ArrowRight className="w-3 h-3 text-muted-foreground/30 absolute right-[-10px] top-1/2 -translate-y-1/2 hidden lg:block" />
                    )}
                  </button>
                );
              })}
            </div>
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </section>

        {/* Epic Details — Accordion */}
        <section className="mb-20">
          <Accordion type="single" collapsible value={activeEpic} onValueChange={(v) => v && setActiveEpic(v)}>
            {epics.map((epic) => {
              const Icon = epic.icon;
              return (
                <AccordionItem key={epic.num} value={String(epic.num)} className="border-border/30">
                  <AccordionTrigger className="hover:no-underline py-5">
                    <div className="flex items-center gap-3">
                      <div className={`inline-flex p-2 rounded-lg ${epic.bg}`}>
                        <Icon className={`w-4 h-4 ${epic.color}`} />
                      </div>
                      <span className="font-display text-base text-foreground">
                        Epic {epic.num} — {epic.title}
                      </span>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent>
                    <ul className="space-y-2 pl-12">
                      {epic.details.map((d, i) => (
                        <li key={i} className="flex items-start gap-2 text-muted-foreground font-body text-sm">
                          <span className="text-primary mt-1">•</span>
                          {d}
                        </li>
                      ))}
                    </ul>
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        </section>

        {/* Subscription Tiers */}
        <section>
          <h2 className="font-display text-sm uppercase tracking-[0.2em] text-muted-foreground mb-6">
            Subscription Tiers
          </h2>
          <div className="glass-card overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="border-border/30">
                  <TableHead className="font-display text-xs uppercase tracking-widest text-muted-foreground">Feature</TableHead>
                  {tiers.map((t) => (
                    <TableHead key={t.name} className="text-center font-display text-xs uppercase tracking-widest text-muted-foreground">
                      <div>{t.name}</div>
                      <div className="text-foreground font-body text-sm font-semibold mt-1">{t.price}</div>
                    </TableHead>
                  ))}
                </TableRow>
              </TableHeader>
              <TableBody>
                {Object.keys(featureLabels).map((key) => (
                  <TableRow key={key} className="border-border/20">
                    <TableCell className="font-body text-sm text-muted-foreground">{featureLabels[key]}</TableCell>
                    {tiers.map((t) => (
                      <TableCell key={t.name} className="text-center">
                        <FeatureValue value={t.features[key as keyof typeof t.features]} />
                      </TableCell>
                    ))}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>
      </main>
    </div>
  );
};

const Ventures = () => (
  <AuthGuard>
    <VenturesContent />
  </AuthGuard>
);

export default Ventures;
