import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft, ArrowRight, Rocket, Lock, CreditCard, Hammer, Brain, Globe,
  BarChart3, Shield, Fingerprint, Check, X, Users, Bot, Search, LayoutDashboard,
  MessageSquare, Target, ClipboardList, BadgeCheck, IdCard, MapPin, Briefcase,
  GraduationCap, Star, Wallet, ShieldCheck, Network
} from "lucide-react";
import AuthGuard from "@/components/AuthGuard";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";

// ─── Product Definitions ───────────────────────────────────────────────

type Product = {
  id: string;
  title: string;
  subtitle: string;
  icon: typeof Rocket;
  color: string;
  bg: string;
  description: string;
  epics: Epic[];
  tiers?: Tier[];
};

type Epic = {
  num: number;
  title: string;
  icon: typeof Rocket;
  color: string;
  bg: string;
  details: string[];
};

type Tier = {
  name: string;
  price: string;
  features: Record<string, string | boolean>;
};

// ─── Resume Portfolio (existing) ───────────────────────────────────────

const resumeEpics: Epic[] = [
  { num: 1, title: "Landing Page", icon: Rocket, color: "text-primary", bg: "bg-primary/10", details: ["Hero with value proposition", "Product demo / interactive preview", "Social proof & testimonials", "CTA to sign up"] },
  { num: 2, title: "Auth & Login", icon: Lock, color: "text-primary", bg: "bg-primary/10", details: ["Email/password signup and login", "OAuth (Google, Apple)", "Email verification flow", "Password reset"] },
  { num: 3, title: "Subscriptions", icon: CreditCard, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Free, Pro ($9/mo), Premium ($19/mo), Enterprise tiers", "Stripe integration for billing", "Usage-based limits per tier", "Upgrade / downgrade flows"] },
  { num: 4, title: "Resume Builder", icon: Hammer, color: "text-primary", bg: "bg-primary/10", details: ["AI-powered layout & theme selector (guided wizard)", "Upload artifacts: old resumes, interview answers, metrics", "Drag-and-drop section editor (non-technical friendly)", "Real-time preview with multiple layouts", "Template library (modern, classic, creative, minimal)"] },
  { num: 5, title: "AI Tailoring", icon: Brain, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Paste a JD — AI tailors resume to match", "Keyword optimization & gap analysis", "Tone and language adjustment", "AI resume agent: conversational chatbot for visitors", "Powered by the Dark Factory agentic workflow"] },
  { num: 6, title: "Publish & Share", icon: Globe, color: "text-primary", bg: "bg-primary/10", details: ["One-click publish to yourname.agenticresume.com", "Custom domain support", "Link social media (LinkedIn, GitHub, portfolio)", "QR code generation", "PDF export"] },
  { num: 7, title: "Analytics & SEO", icon: BarChart3, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["View count, unique visitors, time on page", "Section attention heatmap", "SEO meta tags auto-generated by AI", "Open Graph image generation", "Sitemap & robots.txt auto-configured"] },
  { num: 8, title: "Security", icon: Shield, color: "text-primary", bg: "bg-primary/10", details: ["SOC 2 awareness / encryption at rest", "Row-level security on all user data", "GDPR-compliant data handling", "Password-protected resume sharing", "Rate limiting on public endpoints"] },
  { num: 9, title: "Digital Credentials", icon: Fingerprint, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Identity Verification — Government-issued digital IDs (mDL via ISO 18013-5, national eID, eIDAS 2.0)", "Address Verification — Verifiable address credentials from utility providers or government registries", "Educational Credentials — Digital diplomas & transcripts via W3C Verifiable Credentials", "Work Credentials — Employer-issued verifiable credentials (LinkedIn Verified, W3C VC-based employment attestations)", "Built on W3C Verifiable Credentials & OpenID for Verifiable Credentials (OID4VC)"] },
];

const resumeTiers: Tier[] = [
  { name: "Free", price: "$0", features: { resumes: "1", templates: "Basic", customDomain: false, aiTailoring: false, resumeAgent: false, analytics: false, support: "Community", api: false } },
  { name: "Pro", price: "$9/mo", features: { resumes: "Unlimited", templates: "All", customDomain: true, aiTailoring: "Limited", resumeAgent: false, analytics: false, support: "Email", api: false } },
  { name: "Premium", price: "$19/mo", features: { resumes: "Unlimited", templates: "All", customDomain: true, aiTailoring: "Unlimited", resumeAgent: true, analytics: true, support: "Priority", api: false } },
  { name: "Enterprise", price: "Custom", features: { resumes: "Unlimited", templates: "All + Custom", customDomain: true, aiTailoring: "Unlimited", resumeAgent: true, analytics: true, support: "Dedicated", api: true } },
];

// ─── Agentic Recruiter ────────────────────────────────────────────────

const recruiterEpics: Epic[] = [
  { num: 1, title: "Account & Subscription", icon: Users, color: "text-primary", bg: "bg-primary/10", details: ["Recruiter account creation with company profile", "Subscription tiers (Starter, Professional, Enterprise)", "Stripe-powered billing and seat management", "Team invitations and role-based access"] },
  { num: 2, title: "Job Posting Agent", icon: Bot, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Conversational agent guides recruiter through job creation", "Extracts role requirements, salary bands, and culture fit", "Auto-generates structured job descriptions", "Supports bulk posting across the network"] },
  { num: 3, title: "Competency Framework", icon: Target, color: "text-primary", bg: "bg-primary/10", details: ["Configure evaluation criteria per role", "Strategic thinking assessment parameters", "Motivation & drive evaluation metrics", "Promote & trust competency indicators", "Growing people / mentorship scoring", "Leading change adaptability measures"] },
  { num: 4, title: "AI Clarification Agent", icon: MessageSquare, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Asks targeted follow-up questions to refine search", "Narrows candidate pool based on recruiter responses", "Learns preferences over time for better matches", "Suggests adjacent skills and alternative qualifications"] },
  { num: 5, title: "Candidate Search & Matching", icon: Search, color: "text-primary", bg: "bg-primary/10", details: ["Scans the entire Agentic Resume Portfolio network", "AI-powered semantic matching beyond keyword search", "Competency-weighted scoring algorithm", "Filters by verified credentials, location, experience"] },
  { num: 6, title: "Results Dashboard", icon: LayoutDashboard, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Ranked candidate list with match scores", "Side-by-side candidate comparison", "Competency radar charts per candidate", "Shortlist and reject with one click"] },
  { num: 7, title: "Recruitment CRM", icon: ClipboardList, color: "text-primary", bg: "bg-primary/10", details: ["Pipeline stages: Sourced → Screening → Interview → Offer → Hired", "Notes, tags, and activity timeline per candidate", "Interview scheduling with calendar integration", "Automated outreach sequences and templates"] },
  { num: 8, title: "Credential Verification", icon: BadgeCheck, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["One-click verification of candidate credentials", "Trust score based on verified vs. unverified claims", "Integration with the Verified Credentials Portal", "Compliance audit trail for every verification"] },
];

// ─── Verified Credentials Portal ──────────────────────────────────────

const credentialEpics: Epic[] = [
  { num: 1, title: "Identity Verification", icon: IdCard, color: "text-primary", bg: "bg-primary/10", details: ["Government-issued digital IDs (mDL via ISO 18013-5)", "National eID and eIDAS 2.0 compliance", "Biometric liveness detection", "Cross-border identity recognition"] },
  { num: 2, title: "Address Verification", icon: MapPin, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Utility provider-issued address credentials", "Government registry verification", "Geo-validated address attestations", "Privacy-preserving proof of residence"] },
  { num: 3, title: "Employment History", icon: Briefcase, color: "text-primary", bg: "bg-primary/10", details: ["Employer-issued verifiable credentials", "W3C VC-based employment attestations", "LinkedIn Verified integration", "Continuous employment verification (not just point-in-time)"] },
  { num: 4, title: "Education Credentials", icon: GraduationCap, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Digital diplomas via W3C Verifiable Credentials", "MIT Digital Credentials / Hyland integration", "Open Badges v3 support", "Micro-credentials and certifications"] },
  { num: 5, title: "Testimonials & References", icon: Star, color: "text-primary", bg: "bg-primary/10", details: ["Cryptographically signed reference letters", "Peer endorsements with verifiable attribution", "Manager testimonials tied to employment credentials", "Reputation score aggregation"] },
  { num: 6, title: "Wallet Integration", icon: Wallet, color: "text-amber-warm", bg: "bg-amber-warm/10", details: ["Apple Wallet credential storage", "Google Wallet credential storage", "Self-sovereign identity wallet support", "Selective disclosure — share only what's needed"] },
  { num: 7, title: "Recruiter Verification API", icon: ShieldCheck, color: "text-primary", bg: "bg-primary/10", details: ["REST/GraphQL API for credential verification", "Real-time trust score computation", "Batch verification for large candidate pools", "Compliance reporting and audit logs"] },
];

// ─── Products Array ───────────────────────────────────────────────────

const products: Product[] = [
  {
    id: "resume",
    title: "Agentic Resume Portfolio",
    subtitle: "The Job-Seeker Experience",
    icon: Globe,
    color: "text-primary",
    bg: "bg-primary/10",
    description: "AI-powered platform that builds, tailors, and publishes living resume portfolios — complete with a conversational agent that represents you to recruiters.",
    epics: resumeEpics,
    tiers: resumeTiers,
  },
  {
    id: "recruiter",
    title: "Agentic Recruiter",
    subtitle: "The Recruiter Experience",
    icon: Users,
    color: "text-amber-warm",
    bg: "bg-amber-warm/10",
    description: "A subscription-based portal where recruiters post jobs via an AI agent, scan the Resume Portfolio network for matches, and manage the full recruitment lifecycle.",
    epics: recruiterEpics,
  },
  {
    id: "credentials",
    title: "Verified Credentials Portal",
    subtitle: "The Trust Layer",
    icon: ShieldCheck,
    color: "text-primary",
    bg: "bg-primary/10",
    description: "The infrastructure connecting seekers and recruiters — enabling verifiable credentials for identity, employment, education, and more.",
    epics: credentialEpics,
  },
];

const resumeFeatureLabels: Record<string, string> = {
  resumes: "Resumes", templates: "Templates", customDomain: "Custom Domain",
  aiTailoring: "AI Tailoring", resumeAgent: "Resume Agent", analytics: "Analytics",
  support: "Support", api: "API Access",
};

// ─── Sub-Components ───────────────────────────────────────────────────

const FeatureValue = ({ value }: { value: string | boolean }) => {
  if (typeof value === "boolean") {
    return value ? <Check className="w-4 h-4 text-primary mx-auto" /> : <X className="w-4 h-4 text-muted-foreground/40 mx-auto" />;
  }
  return <span className="text-foreground font-body text-sm">{value}</span>;
};

const FlowDiagram = () => (
  <div className="flex flex-col md:flex-row items-center justify-center gap-4 md:gap-6 py-8">
    <div className="glass-card px-5 py-3 text-center">
      <Globe className="w-5 h-5 text-primary mx-auto mb-1" />
      <p className="font-display text-xs text-foreground">Job Seekers</p>
    </div>
    <ArrowRight className="w-5 h-5 text-muted-foreground/40 rotate-90 md:rotate-0" />
    <div className="glass-card px-5 py-3 text-center ring-1 ring-primary/20">
      <Rocket className="w-5 h-5 text-primary mx-auto mb-1" />
      <p className="font-display text-xs text-foreground">Resume Portfolio</p>
    </div>
    <ArrowRight className="w-5 h-5 text-muted-foreground/40 rotate-90 md:rotate-0" />
    <div className="glass-card px-5 py-3 text-center ring-1 ring-amber-warm/20">
      <ShieldCheck className="w-5 h-5 text-amber-warm mx-auto mb-1" />
      <p className="font-display text-xs text-foreground">Verified Credentials</p>
    </div>
    <ArrowLeft className="w-5 h-5 text-muted-foreground/40 rotate-90 md:rotate-0" />
    <div className="glass-card px-5 py-3 text-center">
      <Users className="w-5 h-5 text-amber-warm mx-auto mb-1" />
      <p className="font-display text-xs text-foreground">Recruiters</p>
    </div>
  </div>
);

const EpicSection = ({ epics, activeEpic, setActiveEpic }: { epics: Epic[]; activeEpic: string; setActiveEpic: (v: string) => void }) => (
  <>
    <ScrollArea className="w-full mb-8">
      <div className="flex gap-3 pb-4">
        {epics.map((epic, i) => {
          const Icon = epic.icon;
          const isActive = activeEpic === String(epic.num);
          return (
            <button
              key={epic.num}
              onClick={() => setActiveEpic(String(epic.num))}
              className={`glass-card flex-shrink-0 w-44 p-4 text-left transition-all duration-200 ${isActive ? "ring-1 ring-primary/40 scale-[1.03]" : "hover:bg-card/80"}`}
            >
              <div className={`inline-flex p-2 rounded-lg ${epic.bg} mb-2`}>
                <Icon className={`w-4 h-4 ${epic.color}`} />
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono text-muted-foreground">{String(epic.num).padStart(2, "0")}</span>
                <span className="font-display text-sm text-foreground leading-tight">{epic.title}</span>
              </div>
            </button>
          );
        })}
      </div>
      <ScrollBar orientation="horizontal" />
    </ScrollArea>

    <Accordion type="single" collapsible value={activeEpic} onValueChange={(v) => v && setActiveEpic(v)}>
      {epics.map((epic) => {
        const Icon = epic.icon;
        return (
          <AccordionItem key={epic.num} value={String(epic.num)} className="border-border/30">
            <AccordionTrigger className="hover:no-underline py-5">
              <div className="flex items-center gap-3">
                <div className={`inline-flex p-2 rounded-lg ${epic.bg}`}>
                  <Icon className={`w-4 h-4 ${epic.color}`} />
                </div>
                <span className="font-display text-base text-foreground">
                  Epic {epic.num} — {epic.title}
                </span>
              </div>
            </AccordionTrigger>
            <AccordionContent>
              <ul className="space-y-2 pl-12">
                {epic.details.map((d, i) => (
                  <li key={i} className="flex items-start gap-2 text-muted-foreground font-body text-sm">
                    <span className="text-primary mt-1">•</span>
                    {d}
                  </li>
                ))}
              </ul>
            </AccordionContent>
          </AccordionItem>
        );
      })}
    </Accordion>
  </>
);

const TierTable = ({ tiers }: { tiers: Tier[] }) => (
  <div className="mt-12">
    <h3 className="font-display text-sm uppercase tracking-[0.2em] text-muted-foreground mb-6">
      Subscription Tiers
    </h3>
    <div className="glass-card overflow-hidden">
      <Table>
        <TableHeader>
          <TableRow className="border-border/30">
            <TableHead className="font-display text-xs uppercase tracking-widest text-muted-foreground">Feature</TableHead>
            {tiers.map((t) => (
              <TableHead key={t.name} className="text-center font-display text-xs uppercase tracking-widest text-muted-foreground">
                <div>{t.name}</div>
                <div className="text-foreground font-body text-sm font-semibold mt-1">{t.price}</div>
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {Object.keys(resumeFeatureLabels).map((key) => (
            <TableRow key={key} className="border-border/20">
              <TableCell className="font-body text-sm text-muted-foreground">{resumeFeatureLabels[key]}</TableCell>
              {tiers.map((t) => (
                <TableCell key={t.name} className="text-center">
                  <FeatureValue value={t.features[key as keyof typeof t.features]} />
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  </div>
);

// ─── Main Component ───────────────────────────────────────────────────

const VenturesHubContent = () => {
  const [selectedProduct, setSelectedProduct] = useState<string | null>(null);
  const [activeEpic, setActiveEpic] = useState<string>("1");
  const navigate = useNavigate();

  const currentProduct = products.find((p) => p.id === selectedProduct);

  const handleSelectProduct = (id: string) => {
    if (selectedProduct === id) {
      setSelectedProduct(null);
    } else {
      setSelectedProduct(id);
      setActiveEpic("1");
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Top nav */}
      <div className="fixed top-0 left-0 right-0 z-50 bg-background/70 backdrop-blur-xl border-b border-border/50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={() => navigate("/")} className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors font-body text-sm">
            <ArrowLeft className="w-4 h-4" /> Back to Portfolio
          </button>
          <span className="font-display text-lg text-primary tracking-wide">True Hire</span>
        </div>
      </div>

      <main className="pt-24 pb-20 px-6 max-w-6xl mx-auto">
        {/* Master Hero */}
        <header className="text-center mb-8 space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-body font-medium tracking-wide uppercase">
            <Network className="w-3.5 h-3.5" /> True Hire
          </div>
          <h1 className="font-display text-4xl md:text-5xl text-foreground tracking-wide">
            True Hire
          </h1>

          {/* Problem Statement */}
          <div className="max-w-3xl mx-auto glass-card p-6 text-left space-y-3">
            <h2 className="font-display text-sm uppercase tracking-[0.2em] text-primary">The Problem</h2>
            <p className="font-body text-sm text-muted-foreground leading-relaxed">
              Companies can't trust who they're hiring. Candidates lie on resumes, fabricate credentials, 
              swap out between interview and day one, and in some cases are fronts for insider threats. 
              There is no reliable way to verify that the person you interviewed is the person who shows up — 
              or that their background is real.
            </p>
          </div>

          {/* What True Hire Solves */}
          <div className="max-w-3xl mx-auto glass-card p-6 text-left space-y-3">
            <h2 className="font-display text-sm uppercase tracking-[0.2em] text-primary">What True Hire Solves</h2>
            <p className="font-body text-sm text-muted-foreground leading-relaxed">
              True Hire is a three-part recruitment ecosystem that ensures every candidate is real, credentialed, and honest. 
              Job seekers build verified, AI-powered portfolios. Recruiters find and evaluate candidates through an intelligent agent. 
              A credential verification layer connects both sides — so companies know exactly who they're hiring.
            </p>
          </div>
        </header>

        {/* Flow Diagram */}
        <FlowDiagram />

        {/* Product Cards */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-12 mb-12">
          {products.map((product) => {
            const Icon = product.icon;
            const isSelected = selectedProduct === product.id;
            return (
              <button
                key={product.id}
                onClick={() => handleSelectProduct(product.id)}
                className={`glass-card p-6 text-left transition-all duration-300 ${
                  isSelected
                    ? "ring-2 ring-primary/50 scale-[1.02] shadow-lg"
                    : "hover:bg-card/80 hover:scale-[1.01]"
                }`}
              >
                <div className={`inline-flex p-3 rounded-xl ${product.bg} mb-4`}>
                  <Icon className={`w-6 h-6 ${product.color}`} />
                </div>
                <h3 className="font-display text-lg text-foreground mb-1">{product.title}</h3>
                <p className="font-body text-xs uppercase tracking-widest text-muted-foreground mb-3">{product.subtitle}</p>
                <p className="font-body text-sm text-muted-foreground leading-relaxed">{product.description}</p>
                <div className="mt-4 flex items-center gap-1 text-primary font-body text-sm font-medium">
                  {isSelected ? "Collapse" : "Explore"} <ArrowRight className={`w-3.5 h-3.5 transition-transform ${isSelected ? "rotate-90" : ""}`} />
                </div>
              </button>
            );
          })}
        </section>

        {/* Expanded Product Detail */}
        {currentProduct && (
          <section className="animate-in fade-in-0 slide-in-from-top-4 duration-500">
            <div className="border-t border-border/30 pt-12">
              <div className="flex items-center gap-3 mb-8">
                <div className={`inline-flex p-2 rounded-lg ${currentProduct.bg}`}>
                  <currentProduct.icon className={`w-5 h-5 ${currentProduct.color}`} />
                </div>
                <div>
                  <h2 className="font-display text-2xl text-foreground">{currentProduct.title}</h2>
                  <p className="font-body text-sm text-muted-foreground">{currentProduct.subtitle} — User Journey</p>
                </div>
              </div>

              <EpicSection epics={currentProduct.epics} activeEpic={activeEpic} setActiveEpic={setActiveEpic} />

              {currentProduct.tiers && <TierTable tiers={currentProduct.tiers} />}
            </div>
          </section>
        )}
      </main>
    </div>
  );
};

const VenturesHub = () => (
  <AuthGuard>
    <VenturesHubContent />
  </AuthGuard>
);

export default VenturesHub;
